name: Update GoGuardian CRX to Version Branch

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to create orphan branches

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl xmlstarlet libarchive-tools

      - name: Fetch CRX URL and Version from XML
        id: fetch
        run: |
          curl -sL https://ext.goguardian.com/stable.xml -o stable.xml

          # Parse CRX download URL and version
          CRX_URL=$(xmlstarlet sel -N g="http://www.google.com/update2/response" -t -v "//g:updatecheck/@codebase" stable.xml)
          VERSION=$(xmlstarlet sel -N g="http://www.google.com/update2/response" -t -v "//g:updatecheck/@version" stable.xml)

          echo "Found CRX URL: $CRX_URL"
          echo "Version: $VERSION"

          echo "crx_url=$CRX_URL" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Download CRX file
        run: |
          mkdir -p crx
          curl -L "${{ steps.fetch.outputs.crx_url }}" -o crx/extension.crx

      - name: Extract CRX using bsdtar
        run: |
          mkdir -p src
          bsdtar -xf crx/extension.crx -C src

      - name: Create version branch and commit
        run: |
          VERSION="${{ steps.fetch.outputs.version }}"
          BRANCH="$VERSION"

          # Check if the branch already exists on remote
          if git ls-remote --exit-code --heads origin "$BRANCH"; then
            echo "Branch $BRANCH already exists. Skipping push."
            exit 0
          fi

          # Create a new orphan branch
          git checkout --orphan "$BRANCH"
          git rm -rf . > /dev/null 2>&1 || true

          # Stage files under src/
          git add src
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "Add GoGuardian extension version $VERSION"
          git push origin "$BRANCH"
